project_manager/project_manager/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

import os

import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ticket/', include('ticket.urls', namespace='ticket')),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, name='logout'),
    url(r'^$', views.login_user, name='login_user'),
    url(r'^user_redirection/', views.user_redirection),
    url(r'^change_password/', views.change_password, name='change_password'),
]



# for item in os.listdir(settings.GENERATED_APPS_DIR):
#     if os.path.isfile(os.path.join(settings.GENERATED_APPS_DIR, item, '__init__.py')):
#         app_name = '%s' % item
#         u = url(
#             r'^{0}/'.format(app_name),
#             include(
#                 '{0}.urls'.format(app_name),
#                 namespace='{0}'.format(app_name)
#             )
#         )
#         if u not in urlpatterns:
#             urlpatterns.append(u)

project_manager/ticket/urls.py
"""Djangomon url"""
import views

from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^dashboard/$',
    	views.DashboardView.as_view(), name='dashboard'),
    url(r'^user_dashboard/$',
    	views.UserDashboardView.as_view(), name='user_dashboard'),
    url(r'^create/$',
        TicketCreateView.as_view(), name='create'),
    url(r'^delete/$',
        delete_ticket, name='delete'),
    url(r'^user_ticket_list/$',
    	TicketListUserView.as_view(), name='user_tcket_list'),
    url(r'^ticket_list/$',
    	views.TicketListView.as_view(), name='ticket_list'),
    url(r'^update_template/(?P<ticket_id>[^/]+)/$',
        TicketUpdateTemplateView.as_view(), name='update_template'),
    url(r'^update/(?P<ticket_id>[^/]+)/$',
        TicketUpdateView.as_view(), name='update'),
    url(r'^user_detail/(?P<ticket_id>[^/]+)/$',
        TicketDetailUserView.as_view(), name='user_details'),
    url(r'^(?P<ticket_id>[^/]+)/$',
        TicketDetailView.as_view(), name='details')

]

project_manager/base/models.py
from __future__ import unicode_literals
import uuid

from django.utils.translation import ugettext_lazy as _

from django.db import models


class TimeStamp(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)

    class Meta:
        abstract = True


class Contact(TimeStamp):

    contact_name = models.CharField(
        'Contact Name',
        max_length=50, blank=True, null=True)
    company_name = models.CharField(
        'Company Name',
        max_length=50, unique=True)
    pan_no = models.CharField(max_length=50, blank=True, null=True)
    tin_no = models.CharField(max_length=50, blank=True, null=True)
    service_tax_no = models.CharField(max_length=50, blank=True, null=True)
    payment_terms = models.CharField(max_length=100, blank=True, null=True)
    credit_days = models.IntegerField(
        verbose_name=_('Credit Period (Days)'), default=0)
    ph_number1 = models.CharField(
        max_length=50,
        blank=True, null=True, verbose_name=_("Phone No."))
    ph_number2 = models.CharField(
        max_length=50, blank=True, null=True, verbose_name=_("Alternate No."))
    addressline1 = models.CharField(
        max_length=200, verbose_name=_("Addressline 1"), blank=True, null=True)
    addressline2 = models.CharField(
        max_length=200, verbose_name=_("Addressline 2"), blank=True, null=True)
    email = models.EmailField(
        max_length=254, verbose_name=_("E-Mail"), blank=True, null=True)
    zipcode = models.IntegerField(
        verbose_name=_("Zipcode"), blank=True, null=True)
    city = models.CharField(
        max_length=100, verbose_name=_("City"), blank=True, null=True)
    state = models.CharField(
        max_length=100, verbose_name=_("State"), blank=True, null=True)
    country = models.CharField(
        max_length=50, verbose_name=_("Country"), blank=True, null=True)

    class Meta:
        abstract = True

project_manager/ticket/models.py
from __future__ import unicode_literals

from django.db import models

from base.models import TimeStamp

TICKET_TYPE = (
    (1, "Jira Ticket"),
    (2, "Learning"),
    (3, "Training"),
    (4, "Internal Product"),
    (5, "Other"),

)


STATUS = (
    (1, "Not Started"),
    (2, "Completed"),
    (3, "In-Process"),
    (4, "Under-Review"),
)


STATE = (
    (1, "Not Started"),
    (2,"Dev"),
    (3,"QA"),
    (4,"Build"),
    (5,"Deployment"),
    (6, "Others")
)


class Ticket(TimeStamp):

    ticket_type = models.IntegerField(choices=TICKET_TYPE)
    title = models.CharField(max_length=500)
    description = models.TextField(max_length=1000)
    due_date = models.DateField()
    status = models.IntegerField(choices=STATUS)
    assigned_to = models.ManyToManyField('auth.User')

    def __unicode__(self):
        return "{}".format(self.title)

    def assigned_list(self):
        usernames = self.assigned_to.values_list('username', flat=True)
        return ','.join(usernames)

class MileStone(TimeStamp):

    ticket = models.ForeignKey(
        'ticket.Ticket', related_name="milestones")
    comment = models.CharField(max_length=500)
    hr_spent = models.DurationField(default=0)
    user = models.ForeignKey('auth.User')
    current_state = models.IntegerField(choices=STATE)

    def __unicode__(self):
        return "{}".format(self.ticket.title)

project_manager/base/forms.py
from django import forms

class DateRangeForm(forms.Form):
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=True)

project_manager/base/views.py
from django.views.generic import TemplateView, View
from django.contrib import messages
from django.db.models.query import QuerySet
from django.shortcuts import HttpResponseRedirect
from django.core.exceptions import ImproperlyConfigured
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils import timezone

import logging
logger = logging.getLogger(__name__)


class GenericDataGridView(TemplateView):

    """
    GenericDataGridView Base view create pages with data grid
    Required properties:
        "model" Django model object need to be assigned whose data
        is rendered as Data grid table
        "list_display" is python tupple which contains "model" attributes
        to be shown as Data grid table columns
        "template_name" is template path for TemplateView



    Codes to be added in Templates:
    For include datagrid table need into template
        

    Options:
    Use date_range = True , for date range is required
    Use check_box = False to hide check box column in table
    """

    model = None
    template_name = None
    list_display = None
    title = ''
    sub_title = ''
    date_range = False
    detail_url_reverse = ''
    check_box = True
    action_dict = None

    def get_context_data(self, **kwargs):
        if self.model is None and self.list_display is None:
            raise ImproperlyConfigured(
                "GenericDataGridView requires a definition of "
                "'model' and 'list_display' ")
        context = super(GenericDataGridView, self).get_context_data(**kwargs)
        context['object_list'] = self.make_query()
        # context['list_display'] = self.list_display
        if not self.title:
            context['title'] = self.model._meta.verbose_name
        context['title'] = self.title
        context['sub_title'] = self.sub_title
        # list_display_heading = [
        #     self.model._meta.get_field(field).verbose_name for field in self.list_display]
        context['list_display'] = self.list_display
        # Add Date Query
        context['date_range'] = self.date_range
        # Detail URL
        context['detail_url_reverse'] = self.detail_url_reverse
        # For Check Box
        context['check_box'] = self.check_box
        # For dropdown action
        if self.action_dict is not None:
            context['action_dict'] = self.action_dict
            context['action'] = True
        else:
            context['action'] = False
        return context

    def make_query(self, **kwargs):
        """
        Override this method to send custom filtered object

        Example:
        def make_query(self):
            return self.models.objects.filter(created_at=<some_day>)
        """
        if self.model is None:
            raise ImproperlyConfigured(
                "Need specify 'model' ")
        return self.model.objects.all().order_by('-created_at')

    def post(self, request, *args, **kwargs):
        if 'go' in self.request.POST:
            print "GO"
            dispatch = request.POST['action']
            self.for_action_keys = request.POST.getlist('for_action')
            print "lenght {0}".format(len(self.for_action_keys))
            self.request.META['PATH_INFO']
            try:
                method = getattr(self, dispatch)
            except:
                raise AttributeError(
                    "GenericDataGridView has no method '{0}' defined."
                    "Please define method '{0}'".format(dispatch)
                )
            if len(self.for_action_keys) == 0:
                messages.error(
                    request,
                    "Error! Select atlest one item for action"
                )
                return HttpResponseRedirect(
                    self.request.META['PATH_INFO'])
            else:
                return method()
        else:
            context = self.get_context_data(**kwargs)
            context['object_list'] = self.make_date_query(
                request, raw_query=context['object_list'],
                *args, **kwargs)
            context['end_date'] = request.POST["end_date"]
            context['start_date'] = request.POST["start_date"]
            logger.debug("context:{0}".format(context))
            return self.render_to_response(context)

    def make_date_query(self, request, raw_query, *args, **kwargs):
        logger.debug('Making date_query')
        if type(raw_query) is QuerySet:
            logger.debug('Is raw data is QuerySet')
            from base.forms import DateRangeForm
            form = DateRangeForm(request.POST)
            if form.is_valid():
                logger.debug('DateRangeForm is valid')
                to_date = form.cleaned_data['end_date']
                from_date = form.cleaned_data['start_date']
                logger.info("Form is valid with {0}-{1}".format(from_date, to_date))
                if to_date <= timezone.now().date() and from_date <= timezone.now().date():
                    if to_date == from_date:
                        to_date = timezone.datetime.strptime(request.POST["start_date"],"%m/%d/%Y" )
                        object_list = raw_query.filter(
                        created_at__year = to_date.year,
                        created_at__month = to_date.month,
                        created_at__day = to_date.day).order_by('-created_at')
                        return object_list
                    else:
                        # some weired stuff need to add 24hr or day
                        date_range = [from_date,
                                      to_date+timezone.timedelta(hours=24)]
                        object_list = raw_query.filter(created_at__range=date_range).order_by('-created_at')
                        return object_list
                    logger.debug("Date filtered objects: {0}".format(object_list))
                else:
                    logger.debug("Improper Date Range")
                    messages.warning(request,
                                     "Improper dates try other dates")
            else:
                logger.debug("Improper Date Range")
                messages.warning(request,
                                 "Improper dates try other dates")


class GenericModalCreateView(View):

    form_class = None
    success_url = None
    object_name = None
    error_url = None

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests and
        calls form_check() method to process form
        """
        print "+++++++++++++++"
        print "I am in post"
        print "++++++++++++++++"
        if self.form_class is None:
            raise ImproperlyConfigured(
                "GenericModalCreateView requires a definition of "
                "'form_class'")
        return self.form_init(request, *args, **kwargs)

    def form_init(self, request, *args, **kwargs):
        """
        Instantiating a form instance with the passed
        POST variables and then checked for validity.
        """
        form = self.form_class(request.POST)
        print "+++++++"
        print form
        print "+++++++"
        return self.form_check(form, *args, **kwargs)

    def form_check(self, form, *args, **kwargs):
        if form.is_valid():
            logger.debug("Form is valid")
            return self.form_valid(form)
        else:
            logger.debug("Form is invalid %s " % form.errors)
            return self.form_invalid(form)

    def form_invalid(self, form):
        """
        If the form is invalid, re-render the context data with the
        data-filled form and errors.
        """
        msg = form.errors
        print msg
        logger.debug(self.request.POST)
        messages.warning(self.request, msg)
        return HttpResponseRedirect(self.get_error_url())

    def form_valid(self, form):
        """
        If the form is valid, redirect to the supplied URL.
        """
        print "Form valid"
        form.save()
        msg = "Succesfully created new {0} {1}".format(
            self.object_name, form.instance)
        print "Form Saved"
        messages.success(self.request, msg)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        if self.success_url is None:
            raise ImproperlyConfigured(
                "GenericModalCreateView requires either a definition of "
                "'success_url' or get_success_url method")
        return self.success_url

    def get_error_url(self):
        if self.error_url is None:
            return self.get_success_url()
        else:
            return self.error_url


class CustomRedirection(GenericModalCreateView):

    app_url = None
    page_url = None

    def get_success_url(self):
        if self.app_url is None and self.page_url is None:
            raise ImproperlyConfigured(
                "GenericModalCreateView requires either a definition of "
                "'success_url'")
        return "{0}{1}{2}".format(
            self.app_url,
            self.kwargs.get('pk'),
            self.page_url)


class GenericModalUpdateView(CustomRedirection):
    form_class = None
    object_name = None
    model = None
    print 'inside Update',form_class,object_name,model
    def post(self, request, *args, **kwargs):
        print 'inside post====='
        obj = self.model.objects.get(pk=self.kwargs.get('pk'))
        print obj
        form = self.form_class(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            msg = "{0} {1} is updated".format(
                self.object_name, form.instance)
            messages.success(self.request, msg)
        else:
            print form.errors
            print "form is invalid"
            msg = "{0}".format(form.errors)
            messages.warning(self.request, msg)
        return HttpResponseRedirect(self.get_success_url())


class CustomSelfRedirection(GenericModalCreateView):

project_manager/templates/base/base_dasboard_user.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Task Management</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../../../static/css/bootstrap.min.css" rel="stylesheet">


    <!-- MetisMenu CSS -->
    <link href="../../../../static/css/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="../../../../static/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../../../static/css/sb-admin-2.css" rel="stylesheet">


    <!-- Morris Charts CSS -->
    <link href="../../../../static/css/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../../../../static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- DataTables CSS -->
    <link href="../../../../static/css/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="../../../../static/css/dataTables.responsive.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <!--manish-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">Task management</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    Hello {{username | capfirst}}!!
                </li>


                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        {% for assembly in list_of_assemblies_need_tobe_delivered %}
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> {{assembly.assembly_code}}
                                    <span class="pull-right text-muted small">{{assembly.delivery_date}}</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        {% endfor %}
                        <li>
                            <a class="text-center" href="">
                                <strong>See All Critical Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <!-- <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li> -->
                        <!-- <li class="divider"></li> -->
                        <li><a href="/logout/"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="{% url 'ticket:user_dashboard' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <!-- <li> -->
                            <!-- <a href="#"><i class="fa fa-sitemap  fa-fw"></i> Projects<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="">Project Tree</a>
                                </li>
                                <li>
                                    <a href="">Project Tracker</a>
                                </li>
                                <li>
                                    <a href="">Component Tracker</a>
                                </li>
                                <li>
                                    <a href="">Recent Productions</a>
                                </li>
                                <li>
                                    <a href="">Critical Deliveries</a>
                                </li>

                            </ul> -->
                            <!-- /.nav-second-level -->
                        <!-- </li> -->
                        <!-- <li>
                            <a href=""><i class="fa fa-cogs fa-spin"></i> Machines</a>
                        </li> -->
                        <li>
                            <a href="{% url 'ticket:user_tcket_list' %}"><i class="fa fa-users"></i> Task List</a>
                        </li>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            {% block wrapper%}

            {% endblock %}
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../../../../static/js/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../../../static/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../../../../static/js/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="../../../../static/js/raphael-min.js"></script>
    <script src="../../../../static/js/morris.min.js"></script>
    <!--<script src="../../../../static/js/morris-data.js"></script>-->

    <!-- Custom Theme JavaScript -->
    <script src="../../../../static/js/sb-admin-2.js"></script>

    <!-- Bootstrap table javascript -->
    <script src="../../../../static/js/jquery.dataTables.min.js"></script>
    <script src="../../../../static/js/dataTables.bootstrap.min.js"></script>

    <!-- *** This jquery should be always at last *** -->
    <script>
      $(document).ready(function(){
          $('#mytable').DataTable({
                    responsive: true
            });
        });
    </script>
<script>
                $(function() {
                        $( "#id_due_date" ).datepicker({
                                dateFormat: "yy-mm-dd",
                                defaultDate: "+1w",
                                changeMonth: true,
                                numberOfMonths: 2,
                                onClose: function( selectedDate ) {
                                        $( "#id_due_date" ).datepicker( "option", "minDate", selectedDate );
                                }
                        });
                });
        </script>


</body>

</html>