project_manager/project_manager/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

import os

import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ticket/', include('ticket.urls', namespace='ticket')),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, name='logout'),
    url(r'^$', views.login_user, name='login_user'),
    url(r'^user_redirection/', views.user_redirection),
    url(r'^change_password/', views.change_password, name='change_password'),
]



# for item in os.listdir(settings.GENERATED_APPS_DIR):
#     if os.path.isfile(os.path.join(settings.GENERATED_APPS_DIR, item, '__init__.py')):
#         app_name = '%s' % item
#         u = url(
#             r'^{0}/'.format(app_name),
#             include(
#                 '{0}.urls'.format(app_name),
#                 namespace='{0}'.format(app_name)
#             )
#         )
#         if u not in urlpatterns:
#             urlpatterns.append(u)

project_manager/ticket/urls.py
"""Djangomon url"""
import views

from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^dashboard/$',
    	views.DashboardView.as_view(), name='dashboard'),
    url(r'^user_dashboard/$',
    	views.UserDashboardView.as_view(), name='user_dashboard'),
    url(r'^create/$',
        TicketCreateView.as_view(), name='create'),
    url(r'^delete/$',
        delete_ticket, name='delete'),
    url(r'^user_ticket_list/$',
    	TicketListUserView.as_view(), name='user_tcket_list'),
    url(r'^ticket_list/$',
    	views.TicketListView.as_view(), name='ticket_list'),
    url(r'^update_template/(?P<ticket_id>[^/]+)/$',
        TicketUpdateTemplateView.as_view(), name='update_template'),
    url(r'^update/(?P<ticket_id>[^/]+)/$',
        TicketUpdateView.as_view(), name='update'),
    url(r'^user_detail/(?P<ticket_id>[^/]+)/$',
        TicketDetailUserView.as_view(), name='user_details'),
    url(r'^(?P<ticket_id>[^/]+)/$',
        TicketDetailView.as_view(), name='details')

]

project_manager/ticket/models.py
from __future__ import unicode_literals

from django.db import models

from base.models import TimeStamp

TICKET_TYPE = (
    (1, "Jira Ticket"),
    (2, "Learning"),
    (3, "Training"),
    (4, "Internal Product"),
    (5, "Other"),

)


STATUS = (
    (1, "Not Started"),
    (2, "Completed"),
    (3, "In-Process"),
    (4, "Under-Review"),
)


STATE = (
    (1, "Not Started"),
    (2,"Dev"),
    (3,"QA"),
    (4,"Build"),
    (5,"Deployment"),
    (6, "Others")
)


class Ticket(TimeStamp):

    ticket_type = models.IntegerField(choices=TICKET_TYPE)
    title = models.CharField(max_length=500)
    description = models.TextField(max_length=1000)
    due_date = models.DateField()
    status = models.IntegerField(choices=STATUS)
    assigned_to = models.ManyToManyField('auth.User')

    def __unicode__(self):
        return "{}".format(self.title)

    def assigned_list(self):
        usernames = self.assigned_to.values_list('username', flat=True)
        return ','.join(usernames)

class MileStone(TimeStamp):

    ticket = models.ForeignKey(
        'ticket.Ticket', related_name="milestones")
    comment = models.CharField(max_length=500)
    hr_spent = models.DurationField(default=0)
    user = models.ForeignKey('auth.User')
    current_state = models.IntegerField(choices=STATE)

    def __unicode__(self):
        return "{}".format(self.ticket.title)

project_manager/ticket/forms.py
from django import forms
from .models import Ticket, MileStone


class TaskForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = "__all__"

project_manager/ticket/views.py
from django.views.generic import TemplateView
from .models import Ticket, MileStone
from forms import TaskForm
from base.mixin import  GeneralContextMixin, DeleteMixin
from django.shortcuts import HttpResponseRedirect, HttpResponse
from base.views import GenericModalCreateView
from django.contrib import messages


class DashboardView(GeneralContextMixin, TemplateView):

    template_name = 'ticket/dashboard.html'

class UserDashboardView(GeneralContextMixin, TemplateView):

    template_name = 'ticket/user_dashboard.html'

class TicketListView(DeleteMixin, GeneralContextMixin, TemplateView):
    template_name = 'ticket/ticket_list.html'
    model = Ticket
    object_name = 'Ticket'

    def get_context_data(self, **kwargs):
        context = super(TicketListView, self).get_context_data(**kwargs)
        ticket_list = Ticket.objects.all()
        context['ticket_list'] = ticket_list
        context['form'] = TaskForm()
        return context

    def get_success_url(self):
        return ""


# MilestoneListView TicketListUserView
class TicketDetailView(GeneralContextMixin, TemplateView):
    template_name = 'ticket/all_user_details.html'

    def get_context_data(self, **kwargs):
        ticket_id = kwargs.get("ticket_id")
        context = super(TicketDetailView, self).get_context_data(**kwargs)
        detail_list = MileStone.objects.filter(ticket__id=ticket_id)
        ticket = Ticket.objects.get(pk=ticket_id)
        context['ticket'] = ticket
        context['detail_list'] = detail_list
        return context


class TicketDetailUserView(GeneralContextMixin, TemplateView):
    template_name = 'ticket/detail_user.html'

    def get_context_data(self, **kwargs):
        ticket_id = kwargs.get("ticket_id")
        context = super(TicketDetailUserView, self).get_context_data(**kwargs)
        detail_list = MileStone.objects.filter(ticket__id=ticket_id)
        ticket = Ticket.objects.get(pk=ticket_id)
        context['ticket'] = ticket
        context['detail_list'] = detail_list
        return context



class TicketListUserView(GeneralContextMixin, TemplateView):
    template_name = 'ticket/user_tcket_list.html'
    model = Ticket
    object_name = 'Ticket'
    def get_context_data(self, **kwargs):
        user_id = self.request.user
        user_list = Ticket.objects.filter(assigned_to=user_id)
        context = super(TicketListUserView, self).get_context_data(**kwargs)
        context['form'] = TaskForm ()
        context['user_list'] = user_list
        return context

    def get_success_url(self):
        return ""


class TicketCreateView (GenericModalCreateView):
    form_class = TaskForm
    success_url = '/ticket/ticket_list/'


class TicketUpdateView(GeneralContextMixin, GenericModalCreateView):
    form_class = TaskForm
    success_url = '/ticket/ticket_list/'
    object_name = 'TASK'

    def form_init(self, request, *args, **kwargs):
        """
        Instantiating a form instance with the passed
        POST variables and then checked for validity.
        """
        ticket_id = kwargs.get("ticket_id")
        ticket = Ticket.objects.get (pk=ticket_id)
        form = self.form_class (request.POST, instance= ticket)
        return self.form_check (form, *args, **kwargs)

    def form_valid(self, form):
        """
        If the form is valid, redirect to the supplied URL.
        """
        print "Form valid"
        form.save()
        msg = "Succesfully updated {0} {1}".format(
            self.object_name, form.instance)
        print "Form Saved"
        messages.success(self.request, msg)
        return HttpResponseRedirect(self.get_success_url())



class TicketUpdateTemplateView (GeneralContextMixin, TemplateView):
    template_name = 'ticket/update.html'

    def get_context_data(self, **kwargs):
        user_id = self.request.user
        #user_list = Ticket.objects.get('assigned_list')
        #user_list = kwargs.get ("assigned_list")
        user_list = Ticket.objects.filter (assigned_to=user_id)
        #print user_id, '========RUKmini -----==============', user_list
        ticket_id = kwargs.get("ticket_id")
        context = super(TicketUpdateTemplateView, self).get_context_data(**kwargs)
        ticket = Ticket.objects.get(pk=ticket_id)
        context['form'] = TaskForm(instance=ticket)
        context['ticket_id'] = ticket_id
        return context


def delete_ticket(request):
    delete_ids = request.GET.getlist('for_action')
    return HttpResponse('/ticket/ticket_list')


'''
class MilestoneCreateView():
    pass
'''

project_manager/ticket/templates/ticket/all_user_details.html
{% extends "base/base_dashboard.html" %}
{% block wrapper%}
{% if detail_list %}
        <div class="row">
            <h3><u>Task Details</u></h3>
        </div><br><br>
        <div class="row">
            <div class="col-md-8">
                <tbody>
                  <table class="table table-sm">
                      <thead class="thead-dark">
                        <tr>
                          <th scope="col">Comments</th>
                          <th scope="col">Hr_spent</th>
                          <th scope="col">User</th>
                          <th scope="col">Milestone</th>
                        </tr>
                        {% for detail in detail_list %}
                        <tr>
                            <td>{{detail.comment}}</td>
                            <td>{{detail.hr_spent}}</td>
                            <td>{{detail.user}}</td>
                            <td>{{detail.get_current_state_display}}</td>
                        </tr>
                        {% endfor %}
                      </thead>
                  </table>
                </tbody>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                        <li class="list-group-item">Task name:- {{ticket.title}}</li>
                        <li class="list-group-item">Users:- {{ticket.assigned_list}}</li>
                </ul>
            </div>
        </div><br><br>
{% else %}
    <p>No details are available.</p>
{% endif %}
{% endblock %}

project_manager/ticket/templates/ticket/dashboard.html
{% extends "base/base_dashboard.html" %}

{% block wrapper%}
            
{% endblock %}

project_manager/ticket/templates/ticket/detail_user.html
{% extends "base/base_dashboard.html" %}
{% block wrapper%}
{% if detail_list %}
        <div class="row">
            <h3><u>Task Details</u></h3>
        </div><br><br>
        <div class="row">
            <div class="col-md-8">
                <tbody>
                  <table class="table table-sm">
                      <thead class="thead-dark">
                        <tr>
                          <th scope="col">Comments</th>
                          <th scope="col">Hr_spent</th>
                          <th scope="col">User</th>
                          <th scope="col">Milestone</th>
                        </tr>
                        {% for detail in detail_list %}
                        <tr>
                            <td>{{detail.comment}}</td>
                            <td>{{detail.hr_spent}}</td>
                            <td>{{detail.user}}</td>
                            <td>{{detail.get_current_state_display}}</td>
                        </tr>
                        {% endfor %}
                      </thead>
                  </table>
                </tbody>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                        <li class="list-group-item">Task name:- {{ticket.title}}</li>
                        <li class="list-group-item">Users:- {{ticket.assigned_list}}</li>
                </ul>
            </div>
        </div><br><br>
{% else %}
    <p>No details are available.</p>
{% endif %}
{% endblock %}

project_manager/ticket/templates/ticket/ticket_list.html
{% extends "base/base_dashboard.html" %}
{% load crispy_forms_tags %}
    {% block wrapper%}
        {% if ticket_list %}
            <div class="row">
                <h3>Task List</h3>
            </div><br><br>
            <div class="row">
                <div class="col-lg-12">
                    {% if messages %}
                         {% for message in messages %}
                         <div class="alert alert-success" role="alert">
                          <strong>{{ message }}</strong>
                        </div>
                         {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                  <button class="btn btn-primary" data-toggle="modal" data-target="#addapp">Add Task</button>
                  <br><br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                  <form role='form' name='delete' action="" method="post">{% csrf_token %}
                    <tbody>
                        <table class="table table-striped table-bordered" cellspacing="0" width="100%" id="mytable">
                              <thead class="thead-dark">
                                  <tr>
                                      <th scope="col">SlNo.</th>
                                      <th scope="col">Select</th>
                                      <th scope="col">Task Type</th>
                                      <th scope="col">Title</th>
                                      <th scope="col">Description</th>
                                      <th scope="col">Assign To</th>
                                      <th scope="col">Status</th>
                                      <th scope="col">Action</th>
                                  </tr>
                              </thead>
                              {% for ticket in ticket_list %}

                                  <tr>
                                      <td><a href="{% url 'ticket:details' ticket.id %}">TASK-{{forloop.counter}}</a></td>
                                      <td><input type="checkbox" value="{{ticket.id}}" name="for_action"></td>
                                      <td>{{ ticket.get_ticket_type_display }}</td>
                                      <td>{{ticket.title}}</td>
                                      <td>{{ticket.description |truncatechars:20}}</td>
                                      <td>{{ticket.assigned_list}}</td>
                                      <td>{{ticket.get_status_display}}</td>
                                      <td><a href="{% url 'ticket:update_template' ticket.id %}"><i class="fa fa-edit"></i></a></td>
                                  </tr>
                              {% endfor %}
                        </table>
                    </tbody>
                </div>
            </div>
            <div class="row">
              <div class="col-md-3">
                  <button class="btn btn-danger" name="delete" id="del" >Delete</button>
              </div>
              </form>
            </div>

        {% else %}
            <p>No tasks are available.</p>
        {% endif %}

        <!-- Modal -->
                <div class="modal fade" id="addapp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                          <span aria-hidden="true">&times;</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Add Task</h4>
                      </div>
                      <div class="modal-body">
                        <form role='form' action="/ticket/create/" method="post">{% csrf_token %}
                        <div>
                          <input type="text" hidden="" value="{{model_obj_id}}" name="model_obj_id" id="model_obj_id">
                          {{form | crispy}}
                        </div>
                      </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button class="btn btn-primary" >Add</button>
                        </div>
                      </div>
                  </div>
                </div>
                </form>
                <!-- Modal End -->

{% endblock %}

project_manager/ticket/templates/ticket/update.html
{% extends "base/base_dashboard.html" %}
{% load crispy_forms_tags %}
    {% block wrapper%}
        {% if form %}
            <div class="row">
            <!-- Modal -->
                <div class="modal-body">
                    <form role='form' action="/ticket/update/{{ticket_id}}/" method="post">{% csrf_token %}
                        <div>
                            {{form | crispy}}
                        </div>
                </div>
                <div class="modal-footer">
                          <button class="btn btn-primary" >submit</button>
                </div>
            </div>
            </form>
            <!-- Modal End -->
        {% else %}
            <p>No updates are available.</p>
        {% endif %}
{% endblock %}

project_manager/ticket/templates/ticket/user_dashboard.html
{% extends "base/base_dasboard_user.html" %}

{% block wrapper%}
            
{% endblock %}

project_manager/ticket/templates/ticket/user_tcket_list.html
{% extends "base/base_dasboard_user.html" %}
{% load crispy_forms_tags %}
    {% block wrapper%}
        {% if user_list %}
            <div class="row">
                <h3>Task List</h3>
            </div><br><br>
            <div class="row">
                <div class="col-md-12">
                    <tbody>
                        <table class="table table-striped table-bordered" cellspacing="0" width="100%" id="mytable">
                              <thead class="thead-dark">
                                  <tr>
                                      <th scope="col">SlNo.</th>
                                      <th scope="col">Task Type</th>
                                      <th scope="col">Title</th>
                                      <th scope="col">Description</th>
                                      <th scope="col">Assign To</th>
                                      <th scope="col">Status</th>
                                  </tr>
                              </thead>
                              {% for ticket in user_list %}

                                  <tr>
                                      <td><a href="{% url 'ticket:user_details' ticket.id %}">TASK-{{forloop.counter}}</a></td>
                                      <td>{{ ticket.get_ticket_type_display }}</td>
                                      <td>{{ticket.title}}</td>
                                      <td>{{ticket.description |truncatechars:20}}</td>
                                      <td>{{ticket.assigned_list}}</td>
                                      <td>{{ticket.get_status_display}}</td>
                                  </tr>
                              {% endfor %}
                        </table>
                    </tbody>
                </div>
            </div>
        {% endif %}
    {% endblock %}